<?php

include 'boot.php';

$new	= $config === false;
$error	= '';

if( isset($_POST['password']) ) {
	if(empty($_POST['password']))
		$error	= 'Please input password.';
	else{
		if($new){

			$new_config	= array(
					'password' => md5($_POST['password'])
				);
			$comment	= 'This file is auto-generated by script, clear or delete this file to reset password.';
			$str	= "<?php\n" . 
					  "/**\n* $comment\n* Generated at " . date('d M Y H:i:s') . "\n */\n\n" . 
					  '$config	= ' . var_export($new_config, true) . ';';
			if(!file_put_contents('config.php', $str)){
				$error	= 'Cannot write config file, make sure config.php is writtable';
			}else{
				$_SESSION['login']	= true;
				header('Location: editor.php');
				exit;
			}
		}else{
			if(md5($_POST['password']) == $config['password']){
				// OK
				$_SESSION['login']	= true;
				header('Location: editor.php');
				exit;
			}else
			{
				$error	= 'Password not match';
			}
		}
	}
}

?><!doctype html>
<html>
<head>
	<title>Fubon CMS | Login 🔒</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="/assets/css/editor.css" rel="stylesheet">
</head>
<body class="flex justify-center items-center min-h-screen bg-gray-100">
  <div class="w-[280px] text-center shadow-lg">
		<div class="border-b py-8 rounded-t bg-white"><img class="w-[120px] m-auto" src="/assets/img/fubon.svg" alt="Fubon CMS" /></div>
		<form class="space-y-4 px-8 pb-8 pt-6 rounded-b bg-white" method="post">
			<p class="font-medium"><?= $new ? 'Setup new Password' : 'Login to Edit' ?></p>
			<?= $error ? "<p class='text-sm text-gray-500'>$error</p>" : '' ?>
			<input class="w-full h-12 text-xl font-medium rounded border text-center border-gray-300 focus:border-gray-300 ring-0 focus:ring-0 shadow-none" type="password" name="password" autofocus>
			<button class="w-full h-14 font-normal bg-gray-900 hover:bg-black text-white rounded" type="submit">Login</button>
		</form>
	</div>
</body>
</html>